spring.application.name: branding
server.port: 9005
---
spring:
  profiles: default
  cloud.config:
    uri: http://localhost:8888
    label: development
---
spring:
  profiles: development
  cloud.config:
    uri: http://localhost:8888
    label: development
---
spring:
  profiles: test
  cloud.config:
    uri: http://10.128.0.4:8888
    label: test
---
spring:
  profiles: production
  cloud.config.uri: http://10.128.0.2:8888
