spring.application.name: branding
---
spring:
  profiles: default
server.port: ${PORT:9005}
---
spring:
  profiles: development
server.port: ${PORT:9005}
---
spring:
  profiles: production
server.port: ${PORT:443}
server.ssl:
  key-store: classpath:keystore.p12
  keyStoreType: PKCS12
