spring.application.name: branding
---
spring:
  profiles: default
server.port: 9005
---
spring:
  profiles: development
server.port: 9005
---
spring:
  profiles: test
---
spring:
  profiles: production
